version: "3.8"

services:
  postgres:
    image: postgres
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    networks:
      - fastapi-postgres
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: root

  frontend:
    image: react
    build: ./frontend
    depends_on:
      - backend
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - fastapi-react
    # expose:
    #   - "5173"
    ports:
      - "3000:3000"
    command: "npm run dev"

    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    image: api
    build: ./backend
    depends_on:
      - postgres
    volumes:
      - ./backend/:/usr/src/app
    networks:
      - fastapi-postgres
      - fastapi-react
    expose:
      - 8000
    ports:
      - "8000:8000"
    command: "python main.py"
    environment:
      - URL_DATABASE=postgresql+psycopg2://postgres:root@postgres:5432/mydb
    
networks:
  fastapi-postgres:
  fastapi-react:

volumes:
  postgres_data: 