name: Docker Compose Action

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run docker-compose up -d
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"

      - name: Execute tests in the running services
        run: |
          cd frontend
          npm run build --if-present
          npm test
          

      - name: Run docker-compose down
        run: docker-compose down